[env:esp32dev]
platform = espressif32

framework = arduino

; Vitesse du port série pour le moniteur
monitor_speed = 115200

; Aucune bibliothèque externe — tout est bas niveau !
; lib_deps =
board = esp32-s3-devkitc-1
; Ces deux lignes sont essentielles pour l'ESP32-S3 avec USB natif
build_flags = -DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
monitor_port = /dev/ttyACM*