#ifndef TXT_ENEIDE_H
#define TXT_ENEIDE_H

const char *txt_eneide =
    "Je chante les combats et l'homme qui d'abord "
    "Chass\xC3\xA9 par le destin des rivages de Troie "
    "S'en vint en Italie, aux plages laviniennes. "
    "Longtemps les Dieux d'en haut, par la terre et les flots "
    "Le tra\xC3\xAEn\xC3\xA8rent, en proie au courroux de Junon "
    "Et longtemps il p\xC3\xA2tit des malheurs de la guerre "
    "Jusqu'\xC3\xA0 ce qu'il fond\xC3\xA2t sa ville et transport\xC3\xA2t "
    "ses Dieux au Latium d'o\xC3\xB9 la race latine, "
    "les Albins nos a\xC3\xAF" "eux et les hauts murs de Rome. "
    "Muse, rappelle-moi les causes, quelle offense "
    "Quelle blessure a fait que la reine des Dieux "
    "Contraignit ce h\xC3\xA9ros \xC3\xA0 l'insigne pi\xC3\xA9t\xC3\xA9 "
    "A subir tant de maux, \xC3\xA0 souffrir tant d'\xC3\xA9preuve? "
    "Les Dieux connaissent-ils de tels ressentiments? "
    "Une antique cit\xC3\xA9 de colons tyriens "
    "Carthage, regardait l'Italie et, de loin, "
    "L'embouchure du Tibre; elle \xC3\xA9tait opulente, "
    "Et d'une ardeur terrible aux travaux de la guerre. "
    "Junon la pr\xC3\xA9" "f\xC3\xA9rait \xC3\xA0 tout autre s\xC3\xA9jour "
    "Dit-on, m\xC3\xAAme \xC3\xA0 Samos; c'est l\xC3\xA0 qu'\xC3\xA9taient ses armes, "
    "C'est l\xC3\xA0 qu'\xC3\xA9tait son char; et d\xC3\xA9j\xC3\xA0 la d\xC3\xA9" "esse "
    "Travaille avec chaleur \xC3\xA0 lui donner un jour, "
    "Si le destin le veut, l'empire de la terre. "
    "Mais elle avait appris que du sang des Troyens "
    "Une race naissait qui devait renverser "
    "Ce haut r\xC3\xA9" "duit de Tyr, et qu'il en sortirait "
    "Un peuple conqu\xC3\xA9rant, superbe dans la guerre "
    "Funeste \xC3\xA0 la Lybie: ainsi filaient les Parques. "
    "Alarm\xC3\xA9" "e et songeant aux combats que jadis "
    "Elle avait devant Troie affront\xC3\xA9s pour ses Grecs, "
    "Les causes de sa haine et ses peines cuisantes "
    "Demeuraient dans son \xC3\xA2me; elle gardait au c\xC5\x93ur "
    "Le verdict de P\xC3\xA2ris, affront \xC3\xA0 sa beaut\xC3\xA9, "
    "Une race odieuse, enfin de Gany\xC3\xA8" "de "
    "Le rapt et les honneurs. Elle en br\xC3\xBBlait encore "
    "Et sur toute la mer ballottait les Troyens, "
    "Reste des Danan\xC3\xA9" "ens et du cruel Achille, "
    "Bien loin du Latium: et depuis des ann\xC3\xA9" "es "
    "Les destins les poussaient de rivage en rivage. "
    "Tant d'efforts dut co\xC3\xBBter la naissance de Rome! "
    "\xC3\x80 peine hors de vue des c\xC3\xB4tes de Sicile "
    "Ils faisaient voile vers le large, tout joyeux "
    "Et la mer \xC3\xA9" "cumait sous l'\xC3\xA9trave d'\xC3\xA9rain. "
    "Junon, gardant au c\xC5\x93ur sa blessure \xC3\xA9ternelle "
    "Se dit: Moi, m'avouer vaincue, et renoncer "
    "\xC3\x80 fermer l'Italie au roi des Teucriens? "
    "Sans doute les destins m'en emp\xC3\xAA" "chent! Pallas "
    "N'a-t-elle pu br\xC3\xBBler la flotte des Argiens, "
    "N'a-t-elle pu les engloutir au fond des flots "
    "Pour les fureurs du seul Ajax, fils d'O\xC3\xAFl\xC3\xA9" "e? "
    "Elle a lanc\xC3\xA9 du ciel le feu de Jupiter, "
    "Dispers\xC3\xA9 les vaisseaux, boulevers\xC3\xA9 la mer "
    "Et dans un tourbillon saisi le malheureux "
    "Dont le c\xC5\x93ur transperc\xC3\xA9 laissait jaillir des flammes, "
    "Pour le clouer enfin \xC3\xA0 la pointe d'un roc. "
    "Et moi qui chez les dieux m'avance en souveraine, "
    "Qui suis de Jupiter et la s\xC5\x93ur et l'\xC3\xA9pouse, "
    "Je combats seule un peuple, et depuis tant d'ann\xC3\xA9" "e! "
    "Qui voudra de Junon honorer la puissance "
    "Ou charger ses autels d'offrandes suppliantes? "
    "Agitant ces pensers dans son c\xC5\x93ur plein de flamme "
    "Elle gagne \xC3\x89olie, o\xC3\xB9 naissent les orages, "
    "Terre toujours f\xC3\xA9" "conde en autans furieux. "
    "C'est l\xC3\xA0 que dans un antre immense r\xC3\xA8gne \xC3\x89ole; "
    "Sur les vents mutin\xC3\xA9s, les temp\xC3\xAAtes sonores, "
    "Son pouvoir fait peser les fers d'une prison, "
    "Avec un grondement qui remplit la montagne, "
    "Ils hurlent indign\xC3\xA9s derri\xC3\xA8re les verrous. "
    "Assis sur les hauteurs, \xC3\x89ole, sceptre en main, "
    "Refr\xC3\xA8ne leurs \xC3\xA9lans et mod\xC3\xA8re leur rage; "
    "Sinon, la mer, la terre et la vo\xC3\xBBte des cieux, "
    "Ils emporteraient tout dans leurs brusques rafales. "
    "Mais le p\xC3\xA8re des dieux, redoutant ce d\xC3\xA9sastre "
    "Les a emprisonn\xC3\xA9s dans de sombres cavernes, "
    "\xC3\x80 sur eux entass\xC3\xA9 la masse des montagnes, "
    "Leur a donn\xC3\xA9 un roi qui s\xC3\xBBt, selon un pacte, "
    "Les contenir sur ordre ou leur l\xC3\xA2" "cher les r\xC3\xAAnes. "
    "C'est \xC3\xA0 lui que Junon s'adresse, suppliante: "
    "\xC3\x89ole, \xC3\xA0 qui le roi des hommes et des dieux "
    "A donn\xC3\xA9 le pouvoir ou d'apaiser les flots, "
    "Ou de les soulever, sous le souffle des vents, "
    "Naviguant sur les flots de la mer Thyrr\xC3\xA9nienne, "
    "Un peuple qui me hait transporte en Italie, "
    "Avec ses dieux vaincus, Ilion tout entier. "
    "D\xC3\xA9" "cha\xC3\xAEne les autans, submerge ces vaisseaux "
    "Ab\xC3\xAEme-les ou bien disperse ces Troyens "
    "Et jonche de leurs corps la surface des eaux. "
    "Je poss\xC3\xA8" "de quatorze nymphes admirables "
    "Dont D\xC3\xA9iop\xC3\xA9" "e est la beaut\xC3\xA9 la plus parfaite: "
    "Je te l'attacherai par des n\xC5\x93uds \xC3\xA9ternels; "
    "Tu l'auras \xC3\xA0 toi seul pour prix d'un tel service, "
    "Afin qu'\xC3\xA0 tes c\xC3\xB4t\xC3\xA9s s'\xC3\xA9" "coulent ses ann\xC3\xA9" "es "
    "Et que de beaux enfants tu deviennes le p\xC3\xA8re. "
    "Reine, r\xC3\xA9pond \xC3\x89ole, \xC3\xA0 toi d'examiner "
    "Ce que tu veux; \xC3\xA0 moi d'ex\xC3\xA9" "cuter tes ordres. "
    "C'est de toi que je tiens ce que j'ai de pouvoir, "
    "De toi mon sceptre et la faveur de Jupiter "
    "Le lit o\xC3\xB9 je m'\xC3\xA9tends dans le festin des dieux "
    "Et ma puissance sur l'orage et les temp\xC3\xAAtes "
    "Ayant ainsi parl\xC3\xA9, de sa lance qu'il pointe "
    "Il frappe sur les flancs de la montagne creuse. "
    "Ils s'ouvrent, et soudain la cohorte des vents "
    "S'\xC3\xA9lance en tourbillon et souffle sur la terre. "
    "Tous ensemble, l'Eurus, le Notus, l'Africus "
    "F\xC3\xA9" "cond en ouragans s'abattent sur la mer, "
    "L'arrachant tout enti\xC3\xA8re \xC3\xA0 ses profonds ab\xC3\xAEmes "
    "Et roulent vers ses bords des vagues gigantesques. "
    "Clameur des matelots, sifflement des cordages: "
    "Des nuages, soudain, d\xC3\xA9robent la lumi\xC3\xA8re "
    "Aux Troyens; sur la mer s'\xC3\xA9tale une nuit noire "
    "Les cieux tonnent, l'\xC3\xA9" "clair illumine les nues. "
    "Tout pr\xC3\xA9sente aux marins l'image de la mort. "
    "\xC3\x89n\xC3\xA9" "e en un moment sent frissonner ses membres; "
    "Il g\xC3\xA9mit, et tendant vers le ciel ses deux mains, "
    "Il s'\xC3\xA9" "crie: \xC3\x94 trois fois et quatre fois heureux, "
    "Ceux \xC3\xA0 qui fut donn\xC3\xA9" "e, au pied des murs de Troie "
    "La chance de mourir aux yeux de leurs parents! "
    "\xC3\x94 le plus courageux des Grecs, fils de Tyd\xC3\xA9" "e "
    "Que n'ai-je pu tomber dans les champs d'Ilion "
    "Et rendre l'\xC3\xA2me sous tes coups dans les lieux m\xC3\xAAmes "
    "O\xC3\xB9 le farouche Hector sous la lance d'Achille "
    "Trouva la mort, o\xC3\xB9 g\xC3\xAEt l'\xC3\xA9norme Sarp\xC3\xA9" "don, "
    "O\xC3\xB9 dans ses eaux le Simo\xC3\xAFs a charri\xC3\xA9 "
    "Tant de casques, d'\xC3\xA9" "cus et de corps h\xC3\xA9ro\xC3\xAFques! "
    ;

#endif